/*
 * MIME TYPES:
 *  .css          - text/css
 *  .html or .htm - text/html
 *  .js           - text/javascript
 *  .json         - application/json
 */
String strBanner =  "\n\n"
                    "#########################\n"
                    "ESP8266 Server Foundation\n"
                    "                      I2C\n" /*MODIFICATION*/
                    "#########################\n";

String strWiFiCfgExample =  "{"
                            "\"enableStation\":true,"
                            "\"WiFiConnection\":["
                            "{"
                            "\"ssid\":\"ConnectToNetwork\","
                            "\"password\":\"Password\","
                            "\"connect\":true,"
                            "\"hostname\":\"\""
                            "}"
                            "],"
                            "\"enableAP\":true,"
                            "\"softAP\":{"
                            "\"ssid\":\"\","
                            "\"psk\":\"\","
                            "\"channel\":1,"
                            "\"hidden\":true,"
                            "\"max_connection\":4"
                            "}"
                            "}";
String strRestartESP = "<html><head><meta http-equiv=\"refresh\" content=\"20;url=/\" /></head><body><p>Restarting.....</p></body></html>";

String strRedirectToRootHTML = "<html><head><meta http-equiv=\"refresh\" content=\"0;url=/\" /></head><body><p>Redirecting.....</p></body></html>";

String strHttpStyles = "<style>" "\n"
                       ".link { color: blue; text-decoration: none; font-size:5vw; float: left; clear: left;}" "\n"
                       ".link:hover { color: green; }" "\n"
                       "textarea[id=filecontent] { height: 80%; width: 100%; }" "\n" 
                       "</style>" "\n";
String strHttpResponseHead = "<html><head><title>Device Management</title>" + strHttpStyles + "" "\n"
                             "<meta http-equiv='Cache-Control' content='no-cache, no-store, must-revalidate' />" "\n"
                             "<meta http-equiv='Pragma' content='no-cache' />" "\n"
                             "<meta http-equiv='Expires' content='0' />" "\n"
                             "</head>" "\n";
String strHttpResponseFoot = "</html>" "\n";

String strRootHTML = strHttpResponseHead + "<body>" "\n"
                     "<script>" "\n"
                     "function Go()" "\n"
                     "{" "\n"
                     "goButton.href=selector.value;" "\n"
                     "}" "\n"
                     "function fnAddApplicationsToMenu()" "\n"
                     "{" "\n"
                     "  let http = new XMLHttpRequest();" "\n"
                     "  let url = '/api/listspiffs';" "\n"
                     "  http.open('GET', url, true);" "\n"
                     "  http.onreadystatechange = function()" "\n"
                     "    {" "\n"
                     "      if(http.readyState == 4 && http.status == 200)" "\n"
                     "        {" "\n"
                     "          let selectMenu = document.getElementById('selector');" "\n"
                     "          let sd = JSON.parse(http.responseText);" "\n"
                     "          for (let i = 0; i < sd.file.length; i++)" "\n"
                     "            {" "\n"
                     "              let x_fn = sd.file[i].fileName;" "\n"
                     "              if (x_fn.startsWith('/applications/') && x_fn.endsWith('.html'))" "\n"
                     "                {" "\n"
                     "                  let x_op = document.createElement('option');" "\n"
                     "                  x_op.innerText = x_fn.replace('/applications/','');" "\n"
                     "                  x_op.value = x_fn;" "\n"
                     "                  selectMenu.appendChild(x_op);" "\n"
                     "                }" "\n"
                     "            }" "\n"
                     "        }" "\n"
                     "      }" "\n"
                     "  http.send();" "\n"
                     "}" "\n"
                     "fnAddApplicationsToMenu();" "\n"
                     "</script>" "\n"
                     "<style>" "\n"
                     "a[id=goButton] {font-size: 8em; text-decoration: none; border: 3px solid grey; border-radius: 20%;}" "\n"
                     "p {text-align: center;}" "\n"
                     "select[id=selector] {font-size: 10vw; width: 90vw;}" "\n"
                     "div[id=container] {position: absolute;top: 50%;left: 50%;transform: translate(-50%,-50%);}" "\n"
                     "ul[id=dropmenu] {display: none;}" "\n"
                     "</style>" "\n"
                     "<div id='container'>" "\n"
                     "<p>" "\n"
                     "<select id='selector'>" "\n"
                     "<option value='/api/deletespiffsfile' title='Usage:file=[filename]'>Delete SPIFFS File</option>" "\n"
                     "<option value='/applications/editspiffsfile'>Edit SPIFFS File</option>" "\n"
                     "<option value='/api/formatspiffs'>Format SPIFFS</option>" "\n"
                     "<option value='/api/getdata'>Get Data</option>" "\n"
                     "<option value='/api/listspiffs'>List SPIFFS</option>" "\n"
                     "<option value='/api/readeeprom'>Read EEPROM</option>" "\n"
                     "<option value='/api/readspiffsfile' title='Usage:?file=[filename]'>Read SPIFFS File</option>" "\n"
                     "<option value='/api/restartesp'>Restart Device</option>" "\n"
                     "<option value='/api/scani2cbus'>Scan I2C Bus</option>" "\n" /*MODIFICATION*/
                     "<option value='/api/i2creadregister' title='Usage:i2cdevice=[deviceID]&i2cregister=[register]&i2cbytes=[bytesToRead]'>Read I2C Register</option>" "\n" /*MODIFICATION*/
                     "<option value='/api/scannetworks'>Scan Networks</option>" "\n"
                     "<option value='/applications/websocket' selected>Websocket</option>" "\n"
                     "</select>" "\n"
                     "</p>" "\n"
                     "<p>" "\n"
                     "<a href='javascript:void(0);' id='goButton' onclick='javascript:Go();'>Go</a>" "\n"
                     "</p>" "\n"
                     "</div>" "\n"
                     "<ul id='dropmenu'>" "\n"
                     "<li>&nbsp;" "\n"
                     "<ul>" "\n"
                     "<li>api" "\n"
                     "<ul>" "\n"
                     "<li><a href='/api/deletespiffsfile'>Delete SPIFFS File</a></li>" "\n"
                     "<li><a href='/api/formatspiffs'>Format SPIFFS</a></li>" "\n"
                     "<li><a href='/api/getdata'>Get Data</a></li>" "\n"
                     "<li><a href='/api/listspiffs'>List SPIFFS</a></li>" "\n"
                     "<li><a href='/api/readeeprom'>Read EEPROM</a></li>" "\n"
                     "<li><a href='/api/readspiffsfile'>Read SPIFFS File</a></li>" "\n"
                     "<li><a href='/api/restartesp'>Restart Device</a></li>" "\n"
                     "<li><a href='/api/scani2cbus'>Scan I2C Bus</a></li>" "\n" /*MODIFICATION*/
                     "<li><a href='/api/i2creadregister'>Read I2C Register</a></li>" "\n" /*MODIFICATION*/
                     "<li><a href='/api/scannetworks'>Scan Networks</a></li>" "\n"
                     "</ul>" "\n"
                     "</li>" "\n"
                     "<li>applications" "\n"
                     "<ul>" "\n"
                     "<li><a href='/applications/editspiffsfile'>Edit SPIFFS File</a></li>" "\n"
                     "<li><a href='/applications/websocket'>Web Socket</a></li>" "\n"
                     "</ul>" "\n"
                     "</li>" "\n"
                     "</ul>" "\n"
                     "</li>" "\n"
                     "</ul>" "\n"
                     "</body>" "\n" + strHttpResponseFoot;

String strEditSPIFFSfile = strHttpResponseHead + "<body><script type='text/javascript'>" "\n"
                "  function fnGetSPIFFSdir()" "\n"
                "  {" "\n"
                "    let http = new XMLHttpRequest();" "\n"
                "    let url = '/api/listspiffs';" "\n"
                "    http.open('GET', url, true);" "\n"
                "    http.onreadystatechange = function()" "\n"
                "      {" "\n"
                "        if(http.readyState == 4 && http.status == 200)" "\n"
                "          {" "\n"
                "            let dlSf = document.getElementById('SPIFFSfiles');" "\n"
                "            dlSf.innerHTML = '';" "\n"
                "            let sd = JSON.parse(http.responseText);" "\n"
                "            for (let i = 0; i < sd.file.length; i++)" "\n"
                "              {" "\n"
                "                let x_op = document.createElement('option');" "\n"
                "                x_op.value = sd.file[i].fileName;" "\n"
                "                dlSf.appendChild(x_op);" "\n"
                "              }" "\n"
                "          }" "\n"
                "        }" "\n"
                "    http.send();" "\n"
                "  }" "\n"
                "" "\n"
                "  function fnGetFile()" "\n"
                "  {" "\n"
                "    let inputValue = document.getElementById('filename').value;" "\n"
                "    let x = document.getElementById('SPIFFSfiles');" "\n"
                "    for (let i = 0; i < x.options.length; i++)" "\n"
                "    {" "\n"
                "      optionValue = x.options[i].value;" "\n"
                "      if (optionValue == inputValue)" "\n"
                "      {" "\n"
                "        let http = new XMLHttpRequest();" "\n"
                "        let url = '/api/readspiffsfile';" "\n"
                "        let params = 'file=' + inputValue;" "\n"
                "        http.open('POST', url, true);" "\n"
                "        http.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');" "\n"
                "        http.onreadystatechange = function()" "\n"
                "        {" "\n"
                "          if(http.readyState == 4 && http.status == 200)" "\n"
                "          {" "\n"
                "            let jc = JSON.parse(http.responseText);" "\n"
                "            document.getElementById('filecontent').value = jc.content;" "\n"
                "          }" "\n"
                "        }" "\n"
                "        http.send(params);" "\n"
                "      }" "\n"
                "    }" "\n"
                "  }" "\n"
                "" "\n"
                "  function fnDeleteFile()" "\n"
                "  {" "\n"
                "    let inputValue = document.getElementById('filename').value;" "\n"
                "    let http = new XMLHttpRequest();" "\n"
                "    let url = '/api/deletespiffsfile';" "\n"
                "    let params = 'file=' + inputValue;" "\n"
                "    http.open('POST', url, true);" "\n"
                "    http.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');" "\n"
                "    http.onreadystatechange = function()" "\n"
                "     {" "\n"
                "      if(http.readyState == 4 && http.status == 200)" "\n"
                "       {" "\n"
                "        let jc = JSON.parse(http.responseText);" "\n"
                "        alert(http.responseText);" "\n"
                "       }" "\n"
                "     }" "\n"
                "    http.send(params);" "\n"
                "  }" "\n"
                "" "\n"
                "  function fnSaveFile()" "\n"
                "  {" "\n"
                "    let x_filename = document.getElementById('filename').value;" "\n"
                "    let x_content = document.getElementById('filecontent').value;" "\n"
                "    let http = new XMLHttpRequest();" "\n"
                "    let url = '/api/savespiffsfile';" "\n"
                "    let params = {" "\n"
                "                   fileName : x_filename," "\n"
                "                   content : x_content" "\n"
                "                 };" "\n"
                "    http.open('POST', url, true);" "\n"
                "    http.setRequestHeader('Content-type', 'application/json');" "\n"
                "    http.onreadystatechange = function()" "\n"
                "    {" "\n"
                "      if(http.readyState == 4 && http.status == 200)" "\n"
                "      {" "\n"
                "        alert(http.responseText);" "\n"
                "      }" "\n"
                "    }" "\n"
                "    http.send(JSON.stringify(params));" "\n"
                "  }" "\n"
                "  fnGetSPIFFSdir();" "\n"
                "</script>" "\n"
                "<datalist id=SPIFFSfiles>" "\n"
                "</datalist>" "\n"
                "<p>File: <input id='filename' size=60 type=text value='' list=SPIFFSfiles oninput='fnGetFile();'> <input id='btnRefresh' type='button' value='Refresh' onclick='fnGetSPIFFSdir();' /></p>" "\n"
                "<textarea id='filecontent'>" "\n"
                "</textarea>" "\n"
                "<p>&nbsp;</p><p>&nbsp;</p><p><input id='btnDelete' type='button' value='Delete' onclick='fnDeleteFile();'/>  <input id='btnSave' type='button' value='Save' onclick='fnSaveFile()' /></p>" "\n"
                "</body>" "\n" + strHttpResponseFoot;

String strWebSocketHTML = "<html lang='en'>" "\n"
                          "  <head>" "\n"
                          "    <script>" "\n"
                          "      socket = new WebSocket('ws:/' + '/' + location.host + ':81');" "\n"
                          "      socket.onopen = function(e) { document.getElementById('socket_host').innerHTML = location.host; };" "\n"
                          "      socket.onerror = function(e) { document.getElementById('socket_host').innerHTML = 'socket error'; };" "\n"
                          "      socket.onmessage = function(e)" "\n"
                          "        {" "\n"
                          "          x_data = JSON.parse(e.data);" "\n"
                          "          document.getElementById('raw_data').innerHTML = e.data;" "\n"
                          "        };" "\n"
                          "      document.getElementById('socket_host').innerHTML = location.host;" "\n"
                          "    </script>" "\n"
                          "  </head>" "\n"
                          "  <body>" "\n"
                          "    <div>Socket Host: <span id='socket_host'></span></div>" "\n"
                          "    <div>Raw Data</div>" "\n"
                          "    <div id='raw_data'></div>" "\n"
                          "  </body>" "\n"
                          "</html>";
